config/routes.rb
EstOrders::Application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/' => 'devise/sessions#new'
  end

  resources :forgotten_users
  resources :totals
  resources :shippings
  resources :billings
  resources :customer_notes
  resources :customers
  resources :tooling_specifications
  resources :stripe_specifications
  resources :step_repeats
  resources :skids
  resources :security_specs
  resources :sales_terms
  resources :sales_reps
  resources :rfid_inlays
  resources :rfid_inlay_categories
  resources :registration_levels
  resources :proof_costs
  resources :product_formats
  resources :plate_costs
  resources :mat_categories
  resources :materials
  resources :mag_tapes
  resources :mag_ink_types
  resources :machine_stripe_standards
  resources :machine_id_standards
  resources :press_standards
  resources :laminates
  resources :ink_varnishes
  resources :inksignatures
  resources :inkpmscodes
  resources :inkcatagories
  resources :foiltypes
  resources :foils
  resources :encodingstandards
  resources :dietypes
  resources :dies
  resources :coretypes
  resources :cores
  resources :contacts
  resources :companies
  resources :commissions
  resources :boxtypes
  resources :boxes
  resources :binderyspecs
  resources :binderies
  resources :adhesives

end

app/models/adhesive.rb
class Adhesive < ActiveRecord::Base
  #t.string :adhesivedescription
  #t.integer :costperlb
  #t.integer :msiperlb
  #t.string :partnumber
  #t.string :primaryuse

  validates :adhesivedescription, :costperlb, :msiperlb, :presence => true
  validates :costperlb, :msiperlb, :numericality => {:only_integer => true}
end

app/models/billing.rb
class Billing < ActiveRecord::Base
  validates :addressType, :postalCode, :state, :city, :presence => true
  validates :postalCode, :numericality => true
end

app/models/bindery.rb
class Bindery < ActiveRecord::Base
  validates :opdescription, :presence => true
end

app/models/box.rb
class Box < ActiveRecord::Base
  validates :boxtype, :boxesperskid, :cardsperskid, :size, :length, :width, :height, :innercost,
    :outercost, :presence => true
end

app/models/boxtype.rb
class Boxtype < ActiveRecord::Base
  validates :boxid, :boxtype, :presence => true
end

app/models/company.rb
class Company < ActiveRecord::Base
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/core.rb
class Core < ActiveRecord::Base
  validates :generalName, :cost, :presence => true
end

app/models/coretype.rb
class Coretype < ActiveRecord::Base
  validates :matDescription, :material, :presence => true
end

app/models/customer.rb
class Customer < ActiveRecord::Base
end

app/models/die.rb
class Die < ActiveRecord::Base
  validates :dieCatagory, :description, :die_type, :presence => true
end

app/models/dietype.rb
class Dietype < ActiveRecord::Base
  validates :dieDescription, :presence => true
end

app/models/foil.rb
class Foil < ActiveRecord::Base
  validates :description, :foil_type, :presence => true
end

app/models/foiltype.rb
class Foiltype < ActiveRecord::Base
  validates :foiltype_type, :presence => true
end

app/models/laminate.rb
class Laminate < ActiveRecord::Base
  validates :lamAdhesive, :lamDescription, :presence => true
end

app/models/mag_tape.rb
class MagTape < ActiveRecord::Base
  validates :tapeDescription, :tapeId, :presence => true
end

app/models/material.rb
class Material < ActiveRecord::Base
  belongs_to :MatCategory
  validates :vendor, :materialDescription, :materialMsiCost, :presence => true
end

app/models/sales_rep.rb
class SalesRep < ActiveRecord::Base
end

app/models/shipping.rb
class Shipping < ActiveRecord::Base
end

app/models/skid.rb
class Skid < ActiveRecord::Base
  validates :skidDescription, :presence => true
end

app/models/total.rb
class Total < ActiveRecord::Base
  monetize :freight_cost_cents
  monetize :desired_m_cents
  validates :desired_m_cents, :quantity, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController
  # GET /boxes
  # GET /boxes.json
  def index
    @boxes = Box.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @boxes }
    end
  end

  # GET /boxes/1
  # GET /boxes/1.json
  def show
    @box = Box.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @box }
    end
  end

  # GET /boxes/new
  # GET /boxes/new.json
  def new
    @box = Box.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @box }
    end
  end

  # GET /boxes/1/edit
  def edit
    @box = Box.find(params[:id])
  end

  # POST /boxes
  # POST /boxes.json
  def create
    @box = Box.new(params[:box])

    respond_to do |format|
      if @box.save
        format.html { redirect_to @box, notice: 'Box was successfully created.' }
        format.json { render json: @box, status: :created, location: @box }
      else
        format.html { render action: "new" }
        format.json { render json: @box.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /boxes/1
  # PUT /boxes/1.json
  def update
    @box = Box.find(params[:id])

    respond_to do |format|
      if @box.update_attributes(params[:box])
        format.html { redirect_to @box, notice: 'Box was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @box.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boxes/1
  # DELETE /boxes/1.json
  def destroy
    @box = Box.find(params[:id])
    @box.destroy

    respond_to do |format|
      format.html { redirect_to boxes_url }
      format.json { head :ok }
    end
  end
end

app/helpers/boxes_helper.rb
module BoxesHelper
end

app/views/boxes/_form.html.haml
%fieldset
  %legend
    = controller.action_name.capitalize
    Box
  .control-group
    = f.label :boxtype, 'Box Type', :class => 'control-label'
    .controls
      = f.text_field :boxtype, :class => 'text_field'
  .control-group
    = f.label :boxesperskid, 'Boxes Per Skid', :class => 'control-label'
    .controls
      = f.number_field :boxesperskid, :class => 'number_field'
  .control-group
    = f.label :caliper, :class => 'control-label'
    .controls
      = f.text_field :caliper, :class => 'text_field'
  .control-group
    = f.label :cardsperskid, 'Cards Per Skid', :class => 'control-label'
    .controls
      = f.number_field :cardsperskid, :class => 'number_field'
  .control-group
    = f.label :estimateboxselection, 'Estimate Box Selection', :class => 'control-label'
    .controls
      = f.number_field :estimateboxselection, :class => 'number_field'
  .control-group
    = f.label :height, :class => 'control-label'
    .controls
      = f.number_field :height, :class => 'number_field'
  .control-group
    = f.label :innercost, 'Inner Cost', :class => 'control-label'
    .controls
      = f.number_field :innercost, :class => 'number_field'
  .control-group
    = f.label :innerouter, 'Inner Outer', :class => 'control-label'
    .controls
      = f.text_field :innerouter, :class => 'text_field'
  .control-group
    = f.label :innerquantity, 'Inner Qty', :class => 'control-label'
    .controls
      = f.number_field :innerquantity, :class => 'number_field'
  .control-group
    = f.label :internaldescription, 'Internal Description', :class => 'control-label'
    .controls
      = f.text_area :internaldescription, :class => 'text_area'
  .control-group
    = f.label :length, :class => 'control-label'
    .controls
      = f.number_field :length, :class => 'number_field'
  .control-group
    = f.label :maincustomer, 'Main Customer', :class => 'control-label'
    .controls
      = f.text_field :maincustomer, :class => 'text_field'
  .control-group
    = f.label :outercost, 'Outer Cost', :class => 'control-label'
    .controls
      = f.number_field :outercost, :class => 'number_field'
  .control-group
    = f.label :outerquantity, 'Outer Qty', :class => 'control-label'
    .controls
      = f.number_field :outerquantity, :class => 'number_field'
  .control-group
    = f.label :rowshigh, 'Rows High', :class => 'control-label'
    .controls
      = f.number_field :rowshigh, :class => 'number_field'
  .control-group
    = f.label :selectskid, 'Select Skid', :class => 'control-label'
    .controls
      = f.text_field :selectskid, :class => 'text_field'
  .control-group
    = f.label :size, :class => 'control-label'
    .controls
      = f.text_field :size, :class => 'text_field'
  .control-group
    = f.label :width, :class => 'control-label'
    .controls
      = f.number_field :width, :class => 'number_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to "Cancel", boxes_path, :class => 'btn'

app/views/boxes/edit.html.haml
= form_for @box, :html => { :class => "edit_box form-horizontal", :id => "edit_box" } do |f|
  = render :partial => "form", :locals => {:f => f}

app/views/boxes/index.html.haml
%h1 Boxs
%table{:class => "table table-striped"}
  %thead
    %tr
      %th ID
      %th
        = t("activerecord.attributes.box.boxtype", :default => t("activerecord.labels.boxtype", :default => "Boxtype"))
      %th Created at
      %th Actions
  %tbody
    - @boxes.each do |box|
      %tr
        %td= box.id
        %td= link_to box.boxtype, box_path(box)
        %td= box.created_at
        %td
          = link_to "Show", box_path(box), :class => 'btn btn-mini'
          = link_to "Edit", edit_box_path(box), :class => 'btn btn-mini'
          = link_to "Destroy", box_path(box), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}", :class => 'btn btn-mini btn-danger' 

= link_to "New Box", new_box_path, :class => 'btn btn-primary'

app/views/boxes/new.html.haml
= form_for @box, :html => { :class => 'form-horizontal' } do |f|
  = render :partial => "form", :locals => {:f => f}

app/views/boxes/show.html.haml
%label{:class => "label"}= t("activerecord.attributes.box.boxtype", :default => t("activerecord.labels.boxtype", :default => "Boxtype")) + ":"
%p= @box.boxtype
%label{:class => "label"}= t("activerecord.attributes.box.boxesperskid", :default => t("activerecord.labels.boxesperskid", :default => "Boxesperskid")) + ":"
%p= @box.boxesperskid
%label{:class => "label"}= t("activerecord.attributes.box.caliper", :default => t("activerecord.labels.caliper", :default => "Caliper")) + ":"
%p= @box.caliper
%label{:class => "label"}= t("activerecord.attributes.box.cardsperskid", :default => t("activerecord.labels.cardsperskid", :default => "Cardsperskid")) + ":"
%p= @box.cardsperskid
%label{:class => "label"}= t("activerecord.attributes.box.estimateboxselection", :default => t("activerecord.labels.estimateboxselection", :default => "Estimateboxselection")) + ":"
%p= @box.estimateboxselection
%label{:class => "label"}= t("activerecord.attributes.box.height", :default => t("activerecord.labels.height", :default => "Height")) + ":"
%p= @box.height
%label{:class => "label"}= t("activerecord.attributes.box.innercost", :default => t("activerecord.labels.innercost", :default => "Innercost")) + ":"
%p= @box.innercost
%label{:class => "label"}= t("activerecord.attributes.box.innerouter", :default => t("activerecord.labels.innerouter", :default => "Innerouter")) + ":"
%p= @box.innerouter
%label{:class => "label"}= t("activerecord.attributes.box.innerquantity", :default => t("activerecord.labels.innerquantity", :default => "Innerquantity")) + ":"
%p= @box.innerquantity
%label{:class => "label"}= t("activerecord.attributes.box.internaldescription", :default => t("activerecord.labels.internaldescription", :default => "Internaldescription")) + ":"
%p= @box.internaldescription
%label{:class => "label"}= t("activerecord.attributes.box.length", :default => t("activerecord.labels.length", :default => "Length")) + ":"
%p= @box.length
%label{:class => "label"}= t("activerecord.attributes.box.maincustomer", :default => t("activerecord.labels.maincustomer", :default => "Maincustomer")) + ":"
%p= @box.maincustomer
%label{:class => "label"}= t("activerecord.attributes.box.outercost", :default => t("activerecord.labels.outercost", :default => "Outercost")) + ":"
%p= @box.outercost
%label{:class => "label"}= t("activerecord.attributes.box.outerquantity", :default => t("activerecord.labels.outerquantity", :default => "Outerquantity")) + ":"
%p= @box.outerquantity
%label{:class => "label"}= t("activerecord.attributes.box.rowshigh", :default => t("activerecord.labels.rowshigh", :default => "Rowshigh")) + ":"
%p= @box.rowshigh
%label{:class => "label"}= t("activerecord.attributes.box.selectskid", :default => t("activerecord.labels.selectskid", :default => "Selectskid")) + ":"
%p= @box.selectskid
%label{:class => "label"}= t("activerecord.attributes.box.size", :default => t("activerecord.labels.size", :default => "Size")) + ":"
%p= @box.size
%label{:class => "label"}= t("activerecord.attributes.box.width", :default => t("activerecord.labels.width", :default => "Width")) + ":"
%p= @box.width

.form-actions
  = link_to "Back", boxes_path, :class => 'btn'
  = link_to "Edit", edit_box_path(@box), :class => 'btn'
  = link_to "Delete", box_path(@box), :method => "delete", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}", :class => 'btn btn-danger'