config/routes.rb
EstOrders::Application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/' => 'devise/sessions#new'
  end

  resources :forgotten_users
  resources :totals
  resources :shippings
  resources :billings
  resources :customer_notes
  resources :customers
  resources :tooling_specifications
  resources :stripe_specifications
  resources :step_repeats
  resources :skids
  resources :security_specs
  resources :sales_terms
  resources :sales_reps
  resources :rfid_inlays
  resources :rfid_inlay_categories
  resources :registration_levels
  resources :proof_costs
  resources :product_formats
  resources :plate_costs
  resources :mat_categories
  resources :materials
  resources :mag_tapes
  resources :mag_ink_types
  resources :machine_stripe_standards
  resources :machine_id_standards
  resources :press_standards
  resources :laminates
  resources :ink_varnishes
  resources :inksignatures
  resources :inkpmscodes
  resources :inkcatagories
  resources :foiltypes
  resources :foils
  resources :encodingstandards
  resources :dietypes
  resources :dies
  resources :coretypes
  resources :cores
  resources :contacts
  resources :companies
  resources :commissions
  resources :boxtypes
  resources :boxes
  resources :binderyspecs
  resources :binderies
  resources :adhesives

end

app/models/adhesive.rb
class Adhesive < ActiveRecord::Base
  #t.string :adhesivedescription
  #t.integer :costperlb
  #t.integer :msiperlb
  #t.string :partnumber
  #t.string :primaryuse

  validates :adhesivedescription, :costperlb, :msiperlb, :presence => true
  validates :costperlb, :msiperlb, :numericality => {:only_integer => true}
end

app/models/billing.rb
class Billing < ActiveRecord::Base
  validates :addressType, :postalCode, :state, :city, :presence => true
  validates :postalCode, :numericality => true
end

app/models/bindery.rb
class Bindery < ActiveRecord::Base
  validates :opdescription, :presence => true
end

app/models/box.rb
class Box < ActiveRecord::Base
  validates :boxtype, :boxesperskid, :cardsperskid, :size, :length, :width, :height, :innercost,
    :outercost, :presence => true
end

app/models/boxtype.rb
class Boxtype < ActiveRecord::Base
  validates :boxid, :boxtype, :presence => true
end

app/models/company.rb
class Company < ActiveRecord::Base
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/core.rb
class Core < ActiveRecord::Base
  validates :generalName, :cost, :presence => true
end

app/models/coretype.rb
class Coretype < ActiveRecord::Base
  validates :matDescription, :material, :presence => true
end

app/models/customer.rb
class Customer < ActiveRecord::Base
end

app/models/die.rb
class Die < ActiveRecord::Base
  validates :dieCatagory, :description, :die_type, :presence => true
end

app/models/dietype.rb
class Dietype < ActiveRecord::Base
  validates :dieDescription, :presence => true
end

app/models/foil.rb
class Foil < ActiveRecord::Base
  validates :description, :foil_type, :presence => true
end

app/models/foiltype.rb
class Foiltype < ActiveRecord::Base
  validates :foiltype_type, :presence => true
end

app/models/laminate.rb
class Laminate < ActiveRecord::Base
  validates :lamAdhesive, :lamDescription, :presence => true
end

app/models/mag_tape.rb
class MagTape < ActiveRecord::Base
  validates :tapeDescription, :tapeId, :presence => true
end

app/models/material.rb
class Material < ActiveRecord::Base
  belongs_to :MatCategory
  validates :vendor, :materialDescription, :materialMsiCost, :presence => true
end

app/models/shipping.rb
class Shipping < ActiveRecord::Base
end

app/models/skid.rb
class Skid < ActiveRecord::Base
  validates :skidDescription, :presence => true
end

app/models/total.rb
class Total < ActiveRecord::Base
  monetize :freight_cost_cents
  monetize :desired_m_cents
  validates :desired_m_cents, :quantity, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/mag_tapes_controller.rb
class MagTapesController < ApplicationController
  # GET /mag_tapes
  # GET /mag_tapes.json
  def index
    @mag_tapes = MagTape.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mag_tapes }
    end
  end

  # GET /mag_tapes/1
  # GET /mag_tapes/1.json
  def show
    @mag_tape = MagTape.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mag_tape }
    end
  end

  # GET /mag_tapes/new
  # GET /mag_tapes/new.json
  def new
    @mag_tape = MagTape.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mag_tape }
    end
  end

  # GET /mag_tapes/1/edit
  def edit
    @mag_tape = MagTape.find(params[:id])
  end

  # POST /mag_tapes
  # POST /mag_tapes.json
  def create
    @mag_tape = MagTape.new(params[:mag_tape])

    respond_to do |format|
      if @mag_tape.save
        format.html { redirect_to @mag_tape, notice: 'Mag Tape was successfully created.' }
        format.json { render json: @mag_tape, status: :created, location: @mag_tape }
      else
        format.html { render action: "new" }
        format.json { render json: @mag_tape.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mag_tapes/1
  # PUT /mag_tapes/1.json
  def update
    @mag_tape = MagTape.find(params[:id])

    respond_to do |format|
      if @mag_tape.update_attributes(params[:mag_tape])
        format.html { redirect_to @mag_tape, notice: 'Mag tape was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @mag_tape.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mag_tapes/1
  # DELETE /mag_tapes/1.json
  def destroy
    @mag_tape = MagTape.find(params[:id])
    @mag_tape.destroy

    respond_to do |format|
      format.html { redirect_to mag_tapes_url }
      format.json { head :ok }
    end
  end
end

app/helpers/mag_tapes_helper.rb
module MagTapesHelper
end

app/views/mag_tapes/_form.html.haml
%fieldset
  %legend
    = controller.action_name.capitalize
    Mag Tape
  .control-group
    = f.label :costPerMsi, 'Cost Per MSI', :class => 'control-label'
    .controls
      = f.number_field :costPerMsi, :class => 'number_field'
  .control-group
    = f.label :costPerRoll, 'Cost Per Roll', :class => 'control-label'
    .controls
      = f.number_field :costPerRoll, :class => 'number_field'
  .control-group
    = f.label :typeCate, 'Type Cate', :class => 'control-label'
    .controls
      = f.number_field :typeCate, :class => 'number_field'
  .control-group
    = f.label :tapeDescription, 'Tape Description', :class => 'control-label'
    .controls
      = f.text_field :tapeDescription, :class => 'text_field'
  .control-group
    = f.label :tapeId, 'Tape Id', :class => 'control-label'
    .controls
      = f.number_field :tapeId, :class => 'number_field'
  .control-group
    = f.label :tapeLength, 'Tape Length', :class => 'control-label'
    .controls
      = f.number_field :tapeLength, :class => 'number_field'
  .control-group
    = f.label :tapeType, 'Tape Type', :class => 'control-label'
    .controls
      = f.text_field :tapeType, :class => 'text_field'
  .control-group
    = f.label :tapeWidth, 'Tape Width', :class => 'control-label'
    .controls
      = f.number_field :tapeWidth, :class => 'number_field'
  .form-actions
    = f.submit 'Create Mag Tape', :class => 'btn btn-primary'
    = link_to "Cancel", mag_tapes_path, :class => 'btn'

app/views/mag_tapes/edit.html.haml
= form_for @mag_tape, :html => { :class => "edit_mag_tape form-horizontal", :id => "edit_mag_tape" } do |f|
  = render :partial => "form", :locals => {:f => f}

app/views/mag_tapes/index.html.haml
%h1 Mag Tapes
%table{:class => "table table-striped"}
  %thead
    %tr
      %th ID
      %th
        = t("activerecord.attributes.mag_tape.costPerMsi", :default => t("activerecord.labels.costPerMsi", :default => "Costpermsi"))
      %th Created at
      %th Actions
  %tbody
    - @mag_tapes.each do |mag_tape|
      %tr
        %td= mag_tape.id
        %td= link_to mag_tape.costPerMsi, mag_tape_path(mag_tape)
        %td= mag_tape.created_at
        %td
          = link_to "Show", mag_tape_path(mag_tape), :class => 'btn btn-mini'
          = link_to "Edit", edit_mag_tape_path(mag_tape), :class => 'btn btn-mini'
          = link_to "Destroy", mag_tape_path(mag_tape), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}", :class => 'btn btn-mini btn-danger' 

= link_to "New Mag Tape", new_mag_tape_path, :class => 'btn btn-primary'

app/views/mag_tapes/new.html.haml
= form_for @mag_tape, :html => { :class => 'form-horizontal' } do |f|
  = render :partial => "form", :locals => {:f => f}

app/views/mag_tapes/show.html.haml
%label{:class => "label"}= t("activerecord.attributes.mag_tape.costPerMsi", :default => t("activerecord.labels.costPerMsi", :default => "Costpermsi")) + ":"
%p= @mag_tape.costPerMsi
%label{:class => "label"}= t("activerecord.attributes.mag_tape.costPerRoll", :default => t("activerecord.labels.costPerRoll", :default => "Costperroll")) + ":"
%p= @mag_tape.costPerRoll
%label{:class => "label"}= t("activerecord.attributes.mag_tape.typeCate", :default => t("activerecord.labels.typeCate", :default => "Typecate")) + ":"
%p= @mag_tape.typeCate
%label{:class => "label"}= t("activerecord.attributes.mag_tape.tapeDescription", :default => t("activerecord.labels.tapeDescription", :default => "Tapedescription")) + ":"
%p= @mag_tape.tapeDescription
%label{:class => "label"}= t("activerecord.attributes.mag_tape.tapeId", :default => t("activerecord.labels.tapeId", :default => "Tapeid")) + ":"
%p= @mag_tape.tapeId
%label{:class => "label"}= t("activerecord.attributes.mag_tape.tapeLength", :default => t("activerecord.labels.tapeLength", :default => "Tapelength")) + ":"
%p= @mag_tape.tapeLength
%label{:class => "label"}= t("activerecord.attributes.mag_tape.tapeType", :default => t("activerecord.labels.tapeType", :default => "Tapetype")) + ":"
%p= @mag_tape.tapeType
%label{:class => "label"}= t("activerecord.attributes.mag_tape.tapeWidth", :default => t("activerecord.labels.tapeWidth", :default => "Tapewidth")) + ":"
%p= @mag_tape.tapeWidth

.form-actions
  = link_to "Back", mag_tapes_path, :class => 'btn'
  = link_to "Edit", edit_mag_tape_path(@mag_tape), :class => 'btn'
  = link_to "Delete", mag_tape_path(@mag_tape), :method => "delete", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}", :class => 'btn btn-danger'