config/routes.rb
EstOrders::Application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/' => 'devise/sessions#new'
  end

  resources :forgotten_users
  resources :totals
  resources :shippings
  resources :billings
  resources :customer_notes
  resources :customers
  resources :tooling_specifications
  resources :stripe_specifications
  resources :step_repeats
  resources :skids
  resources :security_specs
  resources :sales_terms
  resources :sales_reps
  resources :rfid_inlays
  resources :rfid_inlay_categories
  resources :registration_levels
  resources :proof_costs
  resources :product_formats
  resources :plate_costs
  resources :mat_categories
  resources :materials
  resources :mag_tapes
  resources :mag_ink_types
  resources :machine_stripe_standards
  resources :machine_id_standards
  resources :press_standards
  resources :laminates
  resources :ink_varnishes
  resources :inksignatures
  resources :inkpmscodes
  resources :inkcatagories
  resources :foiltypes
  resources :foils
  resources :encodingstandards
  resources :dietypes
  resources :dies
  resources :coretypes
  resources :cores
  resources :contacts
  resources :companies
  resources :commissions
  resources :boxtypes
  resources :boxes
  resources :binderyspecs
  resources :binderies
  resources :adhesives

end

app/models/adhesive.rb
class Adhesive < ActiveRecord::Base
  #t.string :adhesivedescription
  #t.integer :costperlb
  #t.integer :msiperlb
  #t.string :partnumber
  #t.string :primaryuse

  validates :adhesivedescription, :costperlb, :msiperlb, :presence => true
  validates :costperlb, :msiperlb, :numericality => {:only_integer => true}
end

app/models/billing.rb
class Billing < ActiveRecord::Base
  validates :addressType, :postalCode, :state, :city, :presence => true
  validates :postalCode, :numericality => true
end

app/models/bindery.rb
class Bindery < ActiveRecord::Base
  validates :opdescription, :presence => true
end

app/models/box.rb
class Box < ActiveRecord::Base
  validates :boxtype, :boxesperskid, :cardsperskid, :size, :length, :width, :height, :innercost,
    :outercost, :presence => true
end

app/models/boxtype.rb
class Boxtype < ActiveRecord::Base
  validates :boxid, :boxtype, :presence => true
end

app/models/company.rb
class Company < ActiveRecord::Base
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/core.rb
class Core < ActiveRecord::Base
  validates :generalName, :cost, :presence => true
end

app/models/coretype.rb
class Coretype < ActiveRecord::Base
  validates :matDescription, :material, :presence => true
end

app/models/customer.rb
class Customer < ActiveRecord::Base
end

app/models/die.rb
class Die < ActiveRecord::Base
  validates :dieCatagory, :description, :die_type, :presence => true
end

app/models/dietype.rb
class Dietype < ActiveRecord::Base
  validates :dieDescription, :presence => true
end

app/models/foil.rb
class Foil < ActiveRecord::Base
  validates :description, :foil_type, :presence => true
end

app/models/foiltype.rb
class Foiltype < ActiveRecord::Base
  validates :foiltype_type, :presence => true
end

app/models/laminate.rb
class Laminate < ActiveRecord::Base
  validates :lamAdhesive, :lamDescription, :presence => true
end

app/models/mag_tape.rb
class MagTape < ActiveRecord::Base
  validates :tapeDescription, :tapeId, :presence => true
end

app/models/material.rb
class Material < ActiveRecord::Base
  belongs_to :MatCategory
  validates :vendor, :materialDescription, :materialMsiCost, :presence => true
end

app/models/press_standard.rb
class PressStandard < ActiveRecord::Base
  validates :machineName, :machineID, :presence => true
end

app/models/skid.rb
class Skid < ActiveRecord::Base
  validates :skidDescription, :presence => true
end

app/models/total.rb
class Total < ActiveRecord::Base
  monetize :freight_cost_cents
  monetize :desired_m_cents
  validates :desired_m_cents, :quantity, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/press_standards_controller.rb
class PressStandardsController < ApplicationController
  # GET /press_standards
  # GET /press_standards.json
  def index
    @press_standards = PressStandard.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @press_standards }
    end
  end

  # GET /press_standards/1
  # GET /press_standards/1.json
  def show
    @press_standard = PressStandard.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @press_standard }
    end
  end

  # GET /press_standards/new
  # GET /press_standards/new.json
  def new
    @press_standard = PressStandard.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @press_standard }
    end
  end

  # GET /press_standards/1/edit
  def edit
    @press_standard = PressStandard.find(params[:id])
  end

  # POST /press_standards
  # POST /press_standards.json
  def create
    @press_standard = PressStandard.new(params[:press_standard])

    respond_to do |format|
      if @press_standard.save
        format.html { redirect_to @press_standard, notice: 'Press Standard was successfully created.' }
        format.json { render json: @press_standard, status: :created, location: @press_standard }
      else
        format.html { render action: "new" }
        format.json { render json: @press_standard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /press_standards/1
  # PUT /press_standards/1.json
  def update
    @press_standard = PressStandard.find(params[:id])

    respond_to do |format|
      if @press_standard.update_attributes(params[:press_standard])
        format.html { redirect_to @press_standard, notice: 'Press standard was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @press_standard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /press_standards/1
  # DELETE /press_standards/1.json
  def destroy
    @press_standard = PressStandard.find(params[:id])
    @press_standard.destroy

    respond_to do |format|
      format.html { redirect_to press_standards_url }
      format.json { head :ok }
    end
  end
end

app/helpers/press_standards_helper.rb
module PressStandardsHelper
end

app/views/press_standards/edit.html.haml
= form_for @press_standard, :html => { :class => "edit_press_standard form-horizontal", :id => "edit_press_standard" } do |f|
  = render :partial => "form", :locals => {:f => f}

app/views/press_standards/index.html.haml
%h1 Press Standards
%table{:class => "table table-striped"}
  %thead
    %tr
      %th ID
      %th
        = t("activerecord.attributes.press_standard.ampMaterial", :default => t("activerecord.labels.ampMaterial", :default => "Ampmaterial"))
      %th Created at
      %th Actions
  %tbody
    - @press_standards.each do |press_standard|
      %tr
        %td= press_standard.id
        %td= link_to press_standard.ampMaterial, press_standard_path(press_standard)
        %td= press_standard.created_at
        %td
          = link_to "Show", press_standard_path(press_standard), :class => 'btn btn-mini'
          = link_to "Edit", edit_press_standard_path(press_standard), :class => 'btn btn-mini'
          = link_to "Destroy", press_standard_path(press_standard), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}", :class => 'btn btn-mini btn-danger' 

= link_to "New Press Standard", new_press_standard_path, :class => 'btn btn-primary'

app/views/press_standards/new.html.haml
= form_for @press_standard, :html => { :class => 'form-horizontal' } do |f|
  = render :partial => "form", :locals => {:f => f}

app/views/press_standards/show.html.haml
%label{:class => "label"}= t("activerecord.attributes.press_standard.ampMaterial", :default => t("activerecord.labels.ampMaterial", :default => "Ampmaterial")) + ":"
%p= @press_standard.ampMaterial
%label{:class => "label"}= t("activerecord.attributes.press_standard.ampTime", :default => t("activerecord.labels.ampTime", :default => "Amptime")) + ":"
%p= @press_standard.ampTime
%label{:class => "label"}= t("activerecord.attributes.press_standard.colorMaterial", :default => t("activerecord.labels.colorMaterial", :default => "Colormaterial")) + ":"
%p= @press_standard.colorMaterial
%label{:class => "label"}= t("activerecord.attributes.press_standard.colorTime", :default => t("activerecord.labels.colorTime", :default => "Colortime")) + ":"
%p= @press_standard.colorTime
%label{:class => "label"}= t("activerecord.attributes.press_standard.colorWaste", :default => t("activerecord.labels.colorWaste", :default => "Colorwaste")) + ":"
%p= @press_standard.colorWaste
%label{:class => "label"}= t("activerecord.attributes.press_standard.dieMaterial", :default => t("activerecord.labels.dieMaterial", :default => "Diematerial")) + ":"
%p= @press_standard.dieMaterial
%label{:class => "label"}= t("activerecord.attributes.press_standard.dieSpeed", :default => t("activerecord.labels.dieSpeed", :default => "Diespeed")) + ":"
%p= @press_standard.dieSpeed
%label{:class => "label"}= t("activerecord.attributes.press_standard.dieTime", :default => t("activerecord.labels.dieTime", :default => "Dietime")) + ":"
%p= @press_standard.dieTime
%label{:class => "label"}= t("activerecord.attributes.press_standard.dieWaste", :default => t("activerecord.labels.dieWaste", :default => "Diewaste")) + ":"
%p= @press_standard.dieWaste
%label{:class => "label"}= t("activerecord.attributes.press_standard.folderMaterial", :default => t("activerecord.labels.folderMaterial", :default => "Foldermaterial")) + ":"
%p= @press_standard.folderMaterial
%label{:class => "label"}= t("activerecord.attributes.press_standard.folderSpeed", :default => t("activerecord.labels.folderSpeed", :default => "Folderspeed")) + ":"
%p= @press_standard.folderSpeed
%label{:class => "label"}= t("activerecord.attributes.press_standard.folderTime", :default => t("activerecord.labels.folderTime", :default => "Foldertime")) + ":"
%p= @press_standard.folderTime
%label{:class => "label"}= t("activerecord.attributes.press_standard.folderWaste", :default => t("activerecord.labels.folderWaste", :default => "Folderwaste")) + ":"
%p= @press_standard.folderWaste
%label{:class => "label"}= t("activerecord.attributes.press_standard.headMaterial", :default => t("activerecord.labels.headMaterial", :default => "Headmaterial")) + ":"
%p= @press_standard.headMaterial
%label{:class => "label"}= t("activerecord.attributes.press_standard.headTime", :default => t("activerecord.labels.headTime", :default => "Headtime")) + ":"
%p= @press_standard.headTime
%label{:class => "label"}= t("activerecord.attributes.press_standard.hotStampMaterial", :default => t("activerecord.labels.hotStampMaterial", :default => "Hotstampmaterial")) + ":"
%p= @press_standard.hotStampMaterial
%label{:class => "label"}= t("activerecord.attributes.press_standard.hotStampSpeed", :default => t("activerecord.labels.hotStampSpeed", :default => "Hotstampspeed")) + ":"
%p= @press_standard.hotStampSpeed
%label{:class => "label"}= t("activerecord.attributes.press_standard.hotStampTime", :default => t("activerecord.labels.hotStampTime", :default => "Hotstamptime")) + ":"
%p= @press_standard.hotStampTime
%label{:class => "label"}= t("activerecord.attributes.press_standard.hotStampWaste", :default => t("activerecord.labels.hotStampWaste", :default => "Hotstampwaste")) + ":"
%p= @press_standard.hotStampWaste
%label{:class => "label"}= t("activerecord.attributes.press_standard.inkType", :default => t("activerecord.labels.inkType", :default => "Inktype")) + ":"
%p= @press_standard.inkType
%label{:class => "label"}= t("activerecord.attributes.press_standard.inkTypeSig", :default => t("activerecord.labels.inkTypeSig", :default => "Inktypesig")) + ":"
%p= @press_standard.inkTypeSig
%label{:class => "label"}= t("activerecord.attributes.press_standard.inkTypeVarnish", :default => t("activerecord.labels.inkTypeVarnish", :default => "Inktypevarnish")) + ":"
%p= @press_standard.inkTypeVarnish
%label{:class => "label"}= t("activerecord.attributes.press_standard.inkMaterial", :default => t("activerecord.labels.inkMaterial", :default => "Inkmaterial")) + ":"
%p= @press_standard.inkMaterial
%label{:class => "label"}= t("activerecord.attributes.press_standard.inkTime", :default => t("activerecord.labels.inkTime", :default => "Inktime")) + ":"
%p= @press_standard.inkTime
%label{:class => "label"}= t("activerecord.attributes.press_standard.inlineMaterial", :default => t("activerecord.labels.inlineMaterial", :default => "Inlinematerial")) + ":"
%p= @press_standard.inlineMaterial
%label{:class => "label"}= t("activerecord.attributes.press_standard.inlineSpeed", :default => t("activerecord.labels.inlineSpeed", :default => "Inlinespeed")) + ":"
%p= @press_standard.inlineSpeed
%label{:class => "label"}= t("activerecord.attributes.press_standard.inlineTime", :default => t("activerecord.labels.inlineTime", :default => "Inlinetime")) + ":"
%p= @press_standard.inlineTime
%label{:class => "label"}= t("activerecord.attributes.press_standard.inlineWaste", :default => t("activerecord.labels.inlineWaste", :default => "Inlinewaste")) + ":"
%p= @press_standard.inlineWaste
%label{:class => "label"}= t("activerecord.attributes.press_standard.insertionMaterial", :default => t("activerecord.labels.insertionMaterial", :default => "Insertionmaterial")) + ":"
%p= @press_standard.insertionMaterial
%label{:class => "label"}= t("activerecord.attributes.press_standard.insertionSpeed", :default => t("activerecord.labels.insertionSpeed", :default => "Insertionspeed")) + ":"
%p= @press_standard.insertionSpeed
%label{:class => "label"}= t("activerecord.attributes.press_standard.insertionTime", :default => t("activerecord.labels.insertionTime", :default => "Insertiontime")) + ":"
%p= @press_standard.insertionTime
%label{:class => "label"}= t("activerecord.attributes.press_standard.laminationMaterial", :default => t("activerecord.labels.laminationMaterial", :default => "Laminationmaterial")) + ":"
%p= @press_standard.laminationMaterial
%label{:class => "label"}= t("activerecord.attributes.press_standard.laminationSpeed", :default => t("activerecord.labels.laminationSpeed", :default => "Laminationspeed")) + ":"
%p= @press_standard.laminationSpeed
%label{:class => "label"}= t("activerecord.attributes.press_standard.laminationTime", :default => t("activerecord.labels.laminationTime", :default => "Laminationtime")) + ":"
%p= @press_standard.laminationTime
%label{:class => "label"}= t("activerecord.attributes.press_standard.laminationWaste", :default => t("activerecord.labels.laminationWaste", :default => "Laminationwaste")) + ":"
%p= @press_standard.laminationWaste
%label{:class => "label"}= t("activerecord.attributes.press_standard.machineName", :default => t("activerecord.labels.machineName", :default => "Machinename")) + ":"
%p= @press_standard.machineName
%label{:class => "label"}= t("activerecord.attributes.press_standard.machineID", :default => t("activerecord.labels.machineID", :default => "Machineid")) + ":"
%p= @press_standard.machineID
%label{:class => "label"}= t("activerecord.attributes.press_standard.machineLabor", :default => t("activerecord.labels.machineLabor", :default => "Machinelabor")) + ":"
%p= @press_standard.machineLabor
%label{:class => "label"}= t("activerecord.attributes.press_standard.machineOverhead", :default => t("activerecord.labels.machineOverhead", :default => "Machineoverhead")) + ":"
%p= @press_standard.machineOverhead
%label{:class => "label"}= t("activerecord.attributes.press_standard.machinePitch", :default => t("activerecord.labels.machinePitch", :default => "Machinepitch")) + ":"
%p= @press_standard.machinePitch
%label{:class => "label"}= t("activerecord.attributes.press_standard.machineSpeed", :default => t("activerecord.labels.machineSpeed", :default => "Machinespeed")) + ":"
%p= @press_standard.machineSpeed
%label{:class => "label"}= t("activerecord.attributes.press_standard.machineType", :default => t("activerecord.labels.machineType", :default => "Machinetype")) + ":"
%p= @press_standard.machineType
%label{:class => "label"}= t("activerecord.attributes.press_standard.machineWidth", :default => t("activerecord.labels.machineWidth", :default => "Machinewidth")) + ":"
%p= @press_standard.machineWidth
%label{:class => "label"}= t("activerecord.attributes.press_standard.numberMaterial", :default => t("activerecord.labels.numberMaterial", :default => "Numbermaterial")) + ":"
%p= @press_standard.numberMaterial
%label{:class => "label"}= t("activerecord.attributes.press_standard.numberSpeed", :default => t("activerecord.labels.numberSpeed", :default => "Numberspeed")) + ":"
%p= @press_standard.numberSpeed
%label{:class => "label"}= t("activerecord.attributes.press_standard.numberTime", :default => t("activerecord.labels.numberTime", :default => "Numbertime")) + ":"
%p= @press_standard.numberTime
%label{:class => "label"}= t("activerecord.attributes.press_standard.numberWaste", :default => t("activerecord.labels.numberWaste", :default => "Numberwaste")) + ":"
%p= @press_standard.numberWaste
%label{:class => "label"}= t("activerecord.attributes.press_standard.plateChangeWaste", :default => t("activerecord.labels.plateChangeWaste", :default => "Platechangewaste")) + ":"
%p= @press_standard.plateChangeWaste
%label{:class => "label"}= t("activerecord.attributes.press_standard.plateChangeMaterial", :default => t("activerecord.labels.plateChangeMaterial", :default => "Platechangematerial")) + ":"
%p= @press_standard.plateChangeMaterial
%label{:class => "label"}= t("activerecord.attributes.press_standard.plateChangeTime", :default => t("activerecord.labels.plateChangeTime", :default => "Platechangetime")) + ":"
%p= @press_standard.plateChangeTime
%label{:class => "label"}= t("activerecord.attributes.press_standard.pressSetupMaterial", :default => t("activerecord.labels.pressSetupMaterial", :default => "Presssetupmaterial")) + ":"
%p= @press_standard.pressSetupMaterial
%label{:class => "label"}= t("activerecord.attributes.press_standard.pressSetupTime", :default => t("activerecord.labels.pressSetupTime", :default => "Presssetuptime")) + ":"
%p= @press_standard.pressSetupTime
%label{:class => "label"}= t("activerecord.attributes.press_standard.printStations", :default => t("activerecord.labels.printStations", :default => "Printstations")) + ":"
%p= @press_standard.printStations
%label{:class => "label"}= t("activerecord.attributes.press_standard.rollChangeMaterial", :default => t("activerecord.labels.rollChangeMaterial", :default => "Rollchangematerial")) + ":"
%p= @press_standard.rollChangeMaterial
%label{:class => "label"}= t("activerecord.attributes.press_standard.rollChangeTime", :default => t("activerecord.labels.rollChangeTime", :default => "Rollchangetime")) + ":"
%p= @press_standard.rollChangeTime
%label{:class => "label"}= t("activerecord.attributes.press_standard.rollChangeWaste", :default => t("activerecord.labels.rollChangeWaste", :default => "Rollchangewaste")) + ":"
%p= @press_standard.rollChangeWaste
%label{:class => "label"}= t("activerecord.attributes.press_standard.slitMaterial", :default => t("activerecord.labels.slitMaterial", :default => "Slitmaterial")) + ":"
%p= @press_standard.slitMaterial
%label{:class => "label"}= t("activerecord.attributes.press_standard.slitSpeed", :default => t("activerecord.labels.slitSpeed", :default => "Slitspeed")) + ":"
%p= @press_standard.slitSpeed
%label{:class => "label"}= t("activerecord.attributes.press_standard.slitTime", :default => t("activerecord.labels.slitTime", :default => "Slittime")) + ":"
%p= @press_standard.slitTime
%label{:class => "label"}= t("activerecord.attributes.press_standard.slitWaste", :default => t("activerecord.labels.slitWaste", :default => "Slitwaste")) + ":"
%p= @press_standard.slitWaste
%label{:class => "label"}= t("activerecord.attributes.press_standard.trim", :default => t("activerecord.labels.trim", :default => "Trim")) + ":"
%p= @press_standard.trim
%label{:class => "label"}= t("activerecord.attributes.press_standard.turretMaterial", :default => t("activerecord.labels.turretMaterial", :default => "Turretmaterial")) + ":"
%p= @press_standard.turretMaterial
%label{:class => "label"}= t("activerecord.attributes.press_standard.turretSpeed", :default => t("activerecord.labels.turretSpeed", :default => "Turretspeed")) + ":"
%p= @press_standard.turretSpeed
%label{:class => "label"}= t("activerecord.attributes.press_standard.turretTime", :default => t("activerecord.labels.turretTime", :default => "Turrettime")) + ":"
%p= @press_standard.turretTime
%label{:class => "label"}= t("activerecord.attributes.press_standard.turretWaste", :default => t("activerecord.labels.turretWaste", :default => "Turretwaste")) + ":"
%p= @press_standard.turretWaste

.form-actions
  = link_to "Back", press_standards_path, :class => 'btn'
  = link_to "Edit", edit_press_standard_path(@press_standard), :class => 'btn'
  = link_to "Delete", press_standard_path(@press_standard), :method => "delete", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}", :class => 'btn btn-danger'