config/routes.rb
EstOrders::Application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/' => 'devise/sessions#new'
  end

  resources :forgotten_users
  resources :totals
  resources :shippings
  resources :billings
  resources :customer_notes
  resources :customers
  resources :tooling_specifications
  resources :stripe_specifications
  resources :step_repeats
  resources :skids
  resources :security_specs
  resources :sales_terms
  resources :sales_reps
  resources :rfid_inlays
  resources :rfid_inlay_categories
  resources :registration_levels
  resources :proof_costs
  resources :product_formats
  resources :plate_costs
  resources :mat_categories
  resources :materials
  resources :mag_tapes
  resources :mag_ink_types
  resources :machine_stripe_standards
  resources :machine_id_standards
  resources :press_standards
  resources :laminates
  resources :ink_varnishes
  resources :inksignatures
  resources :inkpmscodes
  resources :inkcatagories
  resources :foiltypes
  resources :foils
  resources :encodingstandards
  resources :dietypes
  resources :dies
  resources :coretypes
  resources :cores
  resources :contacts
  resources :companies
  resources :commissions
  resources :boxtypes
  resources :boxes
  resources :binderyspecs
  resources :binderies
  resources :adhesives

end

app/models/adhesive.rb
class Adhesive < ActiveRecord::Base
  #t.string :adhesivedescription
  #t.integer :costperlb
  #t.integer :msiperlb
  #t.string :partnumber
  #t.string :primaryuse

  validates :adhesivedescription, :costperlb, :msiperlb, :presence => true
  validates :costperlb, :msiperlb, :numericality => {:only_integer => true}
end

app/models/billing.rb
class Billing < ActiveRecord::Base
  validates :addressType, :postalCode, :state, :city, :presence => true
  validates :postalCode, :numericality => true
end

app/models/bindery.rb
class Bindery < ActiveRecord::Base
  validates :opdescription, :presence => true
end

app/models/box.rb
class Box < ActiveRecord::Base
  validates :boxtype, :boxesperskid, :cardsperskid, :size, :length, :width, :height, :innercost,
    :outercost, :presence => true
end

app/models/boxtype.rb
class Boxtype < ActiveRecord::Base
  validates :boxid, :boxtype, :presence => true
end

app/models/company.rb
class Company < ActiveRecord::Base
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/core.rb
class Core < ActiveRecord::Base
  validates :generalName, :cost, :presence => true
end

app/models/coretype.rb
class Coretype < ActiveRecord::Base
  validates :matDescription, :material, :presence => true
end

app/models/customer.rb
class Customer < ActiveRecord::Base
end

app/models/die.rb
class Die < ActiveRecord::Base
  validates :dieCatagory, :description, :die_type, :presence => true
end

app/models/dietype.rb
class Dietype < ActiveRecord::Base
  validates :dieDescription, :presence => true
end

app/models/foil.rb
class Foil < ActiveRecord::Base
  validates :description, :foil_type, :presence => true
end

app/models/foiltype.rb
class Foiltype < ActiveRecord::Base
  validates :foiltype_type, :presence => true
end

app/models/laminate.rb
class Laminate < ActiveRecord::Base
  validates :lamAdhesive, :lamDescription, :presence => true
end

app/models/mag_tape.rb
class MagTape < ActiveRecord::Base
  validates :tapeDescription, :tapeId, :presence => true
end

app/models/material.rb
class Material < ActiveRecord::Base
  belongs_to :MatCategory
  validates :vendor, :materialDescription, :materialMsiCost, :presence => true
end

app/models/sales_rep.rb
class SalesRep < ActiveRecord::Base
end

app/models/shipping.rb
class Shipping < ActiveRecord::Base
end

app/models/skid.rb
class Skid < ActiveRecord::Base
  validates :skidDescription, :presence => true
end

app/models/total.rb
class Total < ActiveRecord::Base
  monetize :freight_cost_cents
  monetize :desired_m_cents
  validates :desired_m_cents, :quantity, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/foils_controller.rb
class FoilsController < ApplicationController
  # GET /foils
  # GET /foils.json
  def index
    @foils = Foil.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @foils }
    end
  end

  # GET /foils/1
  # GET /foils/1.json
  def show
    @foil = Foil.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @foil }
    end
  end

  # GET /foils/new
  # GET /foils/new.json
  def new
    @foil = Foil.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @foil }
    end
  end

  # GET /foils/1/edit
  def edit
    @foil = Foil.find(params[:id])
  end

  # POST /foils
  # POST /foils.json
  def create
    @foil = Foil.new(params[:foil])

    respond_to do |format|
      if @foil.save
        format.html { redirect_to @foil, notice: 'Foil was successfully created.' }
        format.json { render json: @foil, status: :created, location: @foil }
      else
        format.html { render action: "new" }
        format.json { render json: @foil.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /foils/1
  # PUT /foils/1.json
  def update
    @foil = Foil.find(params[:id])

    respond_to do |format|
      if @foil.update_attributes(params[:foil])
        format.html { redirect_to @foil, notice: 'Foil was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @foil.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foils/1
  # DELETE /foils/1.json
  def destroy
    @foil = Foil.find(params[:id])
    @foil.destroy

    respond_to do |format|
      format.html { redirect_to foils_url }
      format.json { head :ok }
    end
  end
end

app/helpers/foils_helper.rb
module FoilsHelper
end

app/views/foils/_form.html.haml
%fieldset
  %legend
    = controller.action_name.capitalize
    /Foil
  .control-group
    = f.label :description, :class => 'control-label'
    .controls
      = f.text_area :description, :class => 'text_area'
  .control-group
    = f.label :length, :class => 'control-label'
    .controls
      = f.number_field :length, :class => 'number_field'
  .control-group
    = f.label :msi, "MSI", :class => 'control-label'
    .controls
      = f.number_field :msi, :class => 'number_field'
  .control-group
    = f.label :foil_type, "Type", :class => 'control-label'
    .controls
      = f.text_field :foil_type, :class => 'text_field'
  .control-group
    = f.label :width, :class => 'control-label'
    .controls
      = f.number_field :width, :class => 'number_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to "Cancel", foils_path, :class => 'btn'

app/views/foils/edit.html.haml
= form_for @foil, :html => { :class => "edit_foil form-horizontal", :id => "edit_foil" } do |f|
  = render :partial => "form", :locals => {:f => f}

app/views/foils/index.html.haml
%h1 Foils
%table{:class => "table table-striped"}
  %thead
    %tr
      %th ID
      %th
        = t("activerecord.attributes.foil.description", :default => t("activerecord.labels.description", :default => "Description"))
      %th Created at
      %th Actions
  %tbody
    - @foils.each do |foil|
      %tr
        %td= foil.id
        %td= link_to foil.description, foil_path(foil)
        %td= foil.created_at
        %td
          = link_to "Show", foil_path(foil), :class => 'btn btn-mini'
          = link_to "Edit", edit_foil_path(foil), :class => 'btn btn-mini'
          = link_to "Destroy", foil_path(foil), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}", :class => 'btn btn-mini btn-danger' 

= link_to "New Foil", new_foil_path, :class => 'btn btn-primary'

app/views/foils/new.html.haml
= form_for @foil, :html => { :class => 'form-horizontal' } do |f|
  = render :partial => "form", :locals => {:f => f}

app/views/foils/show.html.haml
%label{:class => "label"}= t("activerecord.attributes.foil.description", :default => t("activerecord.labels.description", :default => "Description")) + ":"
%p= @foil.description
%label{:class => "label"}= t("activerecord.attributes.foil.length", :default => t("activerecord.labels.length", :default => "Length")) + ":"
%p= @foil.length
%label{:class => "label"}= t("activerecord.attributes.foil.msi", :default => t("activerecord.labels.msi", :default => "Msi")) + ":"
%p= @foil.msi
%label{:class => "label"}= t("activerecord.attributes.foil.type", :default => t("activerecord.labels.type", :default => "Type")) + ":"
%p= @foil.foil_type
%label{:class => "label"}= t("activerecord.attributes.foil.width", :default => t("activerecord.labels.width", :default => "Width")) + ":"
%p= @foil.width

.form-actions
  = link_to "Back", foils_path, :class => 'btn'
  = link_to "Edit", edit_foil_path(@foil), :class => 'btn'
  = link_to "Delete", foil_path(@foil), :method => "delete", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}", :class => 'btn btn-danger'